# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59dc27dd3273b738593ad2deae6d0df80508e8b69334b178e2df7aec885079073a705c75a451e666e67b7e8891edc857b10c8fe04a5e0dc0c814249ba4c1737a

test:
  secret_key_base: 9fbb42fc14be863fccb8b7ec530fc9f005d7c90f0e9128052fe49bb9f2c5a8954cfe96543d2970cf412fc37a1a2d70d42e0ea40c6bd63d8d7daf2cf72230e5b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
